### ISSUE TITLE
Sample ExceptionHandlerApplication not working

### ISSUE THREAD

**Issue by bostandyksoft** [graphql-java-kickstart/samples#207]
Handling of Exception is not working now.

![image](https://user-images.githubusercontent.com/4920442/192187559-7a415994-d0d3-456d-8044-aeee0c5765c3.png)

**Comment by federicorispo** [comment]
Hi @bostandyksoft, I'm closing this issue because the graphql-java-kickstart/graphql-spring-boot has been archived and it is no longer maintained. We encourage you to start using [Spring for GraphQL](https://spring.io/projects/spring-graphql) instead.

However, I investigate the example and I confirm that is not working because in the [ReflectiveGraphQLErrorFactory.java class](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/00b5e3644c5384bc526d60b76f707191703d90c2/graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/error/ReflectiveGraphQLErrorFactory.java#L38) where the method to invoke to handle the exception is not marked as accessible:

```java
method.setAccessible(true);
```
so, when it is invoked the execution fails with an `IllegalAccessException:` extception.
