### ISSUE TITLE
setting async-timeout property is not overriding the default timeout which is 30s

### ISSUE THREAD

**Issue by sritatineni** [graphql-java-kickstart/samples#317]
I'm using 14.1.0 and defined the below graphql property in my application.yaml

graphql:
  servlet:
    exception-handlers-enabled: true
    async-timeout: 120000

To what I read in the documentation and samples provided this should override the default timeout which is 30s but its not working that way. my app still timeouts arround 30s ish

Please assist.

**Comment by federicorispo** [comment]
I confirm that the async-timeout example was broken. I opened a PR to align it with changes made by the latest versions. 

However, I found out that the execution is not stopped when the timeout expires. In the test I added some logs to prove this behaviour:
 
**Hello query**
 ```
INFO 940789 --- [ graphql-exec-1] com.graphql.sample.boot.Query            : Executing query
INFO 940789 --- [onPool-worker-1] com.graphql.sample.boot.Query            : Start Hello query execution
WARN 940789 --- [nio-9000-exec-2] g.k.servlet.HttpRequestInvokerImpl       : GraphQL execution canceled because timeout of 500 millis was reached. The following query was being executed when this happened:
query {
    hello
}

INFO 940789 --- [onPool-worker-1] com.graphql.sample.boot.Query            : Execute Hello query after the sleep
INFO 940789 --- [onPool-worker-1] com.graphql.sample.boot.Query            : End Hello query execution
```

**World query**
```
INFO 940789 --- [ graphql-exec-2] com.graphql.sample.boot.Query            : Start World query execution
WARN 940789 --- [nio-9000-exec-4] g.k.servlet.HttpRequestInvokerImpl       : GraphQL execution canceled because timeout of 500 millis was reached. The following query was being executed when this happened:
query {
    world
}

INFO 940789 --- [nio-9000-exec-4] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
INFO 940789 --- [nio-9000-exec-4] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
INFO 940789 --- [nio-9000-exec-4] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
INFO 940789 --- [ graphql-exec-2] com.graphql.sample.boot.Query            : Execute World query after the sleep
INFO 940789 --- [ graphql-exec-2] com.graphql.sample.boot.Query            : End World query execution
WARN 940789 --- [ graphql-exec-2] g.k.servlet.HttpRequestInvokerImpl       : Cannot write GraphQL response, because the HTTP response is already committed. It most likely timed out.k
 ```
 
 This is caused by the tentative to cancel a CompletableFuture that cannot be stopped (due to its design) but it can only be completed exceptionally, so the execution of the query continues even if the `cancel` method (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#cancel-boolean-) is invoked.
 
 I will keep the example because the timeout works and the future is completed with an execption that it is returned corretly to the client. I will investigate more on how to stop the execution (maybe with a new instrumentation as suggested in [these](https://github.com/graphql-java/graphql-java/issues/75) [discussions](https://github.com/spring-projects/spring-graphql/issues/450).
 
 Thanks for opening the issue!
